version: '3'
services: 
   klevr-agent:
      image: klevry/klevr-agent:latest
      ports: 
         - "18800:18800"
      environment: 
         - K_API_KEY=1231
         - K_PLATFORM=baremetal
         - K_ZONE_ID=13123
         - K_MANAGER_URL="klevr-manager:8090"
      links:
         - klevr-manager
