version: '3'
services:
   klevr-console:
      image: klevry/klevr-console:latest
      ports:
         - "8091:80"
      depends_on:
         - klevr-manager
      environment:
         - KLEVR_MANAGER_IP=[IP_ADDRESS_HERE:PORTNUM_HERE]
