basePath: /
info:
  contact:
    email: ys3gods@gmail.com
    name: mrchopa
  license: {}
  title: Klevr-Manager API
  version: "1.0"
paths:
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: 에이전트 프로세스가 기동시 최초 한번 handshake를 요청하여 에이전트 정보 등록 및 에이전트 실행에 필요한 실행 정보를 반환한다.
      produces:
      - application/json
      summary: 에이전트의 handshake 요청을 받아 처리한다.
      tags:
      - agents
  /temp:
    get:
      consumes:
      - application/json
      description: 에이전트 프로세스가 기동시 최초 한번 handshake를 요청하여 에이전트 정보 등록 및 에이전트 실행에 필요한 실행 정보를 반환한다.
      produces:
      - application/json
      summary: 에이전트의 handshake 요청을 받아 처리한다.
      tags:
      - temp
swagger: "2.0"
